hyperxpro/Brotli4j

.github/workflows/maven.yml, brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/linux-x86_64/build.sh, natives/linux-x86_64/pom.xml, natives/osx-x86_64/build.sh, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-x86_64/build.bat, natives/windows-x86_64/pom.xml, pom.xml
> Changed Native module names.
> Changed build files accordingly.
=> Prepare for v1.3.0 release

.github/workflows/maven.yml, docker/Dockerfile.centos6, docker/docker-compose.yml
As requested by @slandelle, here is a PR for building on Centos6.
=> changes for compiling brotli on old centos6 distro

README.md, brotli4j/pom.xml, natives/linux-aarch64/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-x86_64/pom.xml, pom.xml
=> Prepare for 1.4.2 Release

README.md
=> Add gradle & refactor readme

brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/BrotliCommon.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/CommonJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Local.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Upstream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliDecoderChannel.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliInputStream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/Decoder.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/DecoderJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/DirectDecompress.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/BrotliEncoderChannel.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/BrotliOutputStream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/EncoderJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/PreparedDictionaryGenerator.java, brotli4j/src/test/java/com/aayushatharva/brotli4j/decoder/DecoderTest.java, brotli4j/src/test/java/com/aayushatharva/brotli4j/encoder/BrotliOutputStreamTest.java, brotli4j/src/test/java/com/aayushatharva/brotli4j/encoder/EncoderTest.java
Adding `ByteBuffer` support to minimize garbage creation and improve performance.
Fixes #35
=> Add `ByteBuffer` support

README.md, brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Local.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Upstream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliInputStream.java, natives/linux-aarch64/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-x86_64/pom.xml, pom.xml
Fix minor typos, remove duplication declaration and make `netty-buffer` as `compile` only.
=> Minor improvements and prepare for v1.7.1 release

.github/workflows/maven.yml, README.md, brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/linux-aarch64/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-aarch64/build.sh, natives/osx-aarch64/pom.xml, natives/pom.xml, natives/windows-x86_64/pom.xml, pom.xml
Add Support for Apple Silicon M1
Closes #33
=> Add Support for Apple Silicon M1

brotli4j/pom.xml, natives/linux-aarch64/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-aarch64/pom.xml, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-x86_64/pom.xml, pom.xml
> Add Apple Silicon M1 support
> Upgrade dependencies
=> Prepare for v1.8.0 release

brotli4j/src/main/java/com/aayushatharva/brotli4j/common/BrotliCommon.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/CommonJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Local.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/common/annotations/Upstream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliDecoderChannel.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliInputStream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/Decoder.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/DecoderJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/Decoders.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/DirectDecompress.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/BrotliEncoderChannel.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/BrotliOutputStream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/EncoderJNI.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoders.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/PreparedDictionary.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/PreparedDictionaryGenerator.java
This pull request addresses #53 by removing/replacing GNU GPL license headers.
=> License header cleanup

all/pom.xml, pom.xml
Add BOM which includes all modules of Brotli4j including native modules.
=> Add All-Bom

brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java
Added `brotli4j.library.path` property for specifying native library location, This gives more flexibility to load brotli native library.
=> feat: custom native library location

brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/Decoders.java
seems to me, this implementation was started on C&P basis but never finished/corrected.
Note: this was tested about as much as the original implementation ;-)
=> fix incomplete implementation of decompression with NIO ByteBuffers

README.md, all/pom.xml, brotli4j/pom.xml, docker/Dockerfile11.centos6, natives/linux-aarch64/pom.xml, natives/linux-armv7/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-aarch64/pom.xml, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-x86_64/pom.xml, pom.xml, service/pom.xml
Motivation:
Prepare for v1.12.0 Release
Modification:
Upgraded Netty to 4.1.92.Final and changed versions from v1.11.0 to v1.12.0
Result:
v1.12.0 Release
=> Prepare for v1.12.0 Release

pom.xml
Motivation:
upgrade to latest version of the Surefire plugin 
https://maven.apache.org/surefire/maven-surefire-plugin/
Modification:
Surefire version 3.1.0
Result:
n/a
=> maven surefire 3.1.0

docker/Dockerfile.centos6, docker/Dockerfile11.centos6, docker/Dockerfile17.centos6
Motivation:
Update Docker Maven to 3.8.6
Modification:
Update Docker Maven to 3.8.6
Result:
Updated Docker Maven to 3.8.6
=> Update Docker Maven to 3.8.6

pom.xml
Motivation:
latest release of Junit5
https://junit.org/junit5/docs/current/release-notes/index.html#release-notes
=> junit 5.10.0

.github/workflows/maven.yml, README.md, all/pom.xml, brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/pom.xml, natives/windows-aarch64/build.bat, natives/windows-aarch64/pom.xml, natives/windows-aarch64/src/main/java/com/aayushatharva/brotli4j/windows/aarch64/NativeLoader.java, pom.xml
Motivation:
We should add support for the Windows ARM (aarch64) platform
Modification:
Added Windows ARM support
Result:
Windows ARM support
=> Windows ARM Support

README.md
Motivation:
async-http-client uses brotli4j
Modification:
update README
Result:
README is updated.
=> readme:  add async-http-client

README.md
add 'Apache NiFi' to README file
=> add Apache NiFi to README

README.md
Also thanks for this project! ❤️
=> add sbt-web-brotli to README

.github/workflows/jekyll-gh-pages.yml
Motivation:
Add GitHub pages deployment via Actions
Modification:
Added GitHub Actions workflow
Result:
GitHub pages deployment
=> GitHub pages deployment
