hyperxpro/Brotli4j

brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/linux-aarch64/build.sh, natives/linux-aarch64/pom.xml, natives/pom.xml
[native-linux-aarch64.tgz.txt](https://github.com/hyperxpro/Brotli4j/files/5951801/native-linux-aarch64.tgz.txt)
Here is a TGZ file of /home/ubuntu/.m2/repository/com/aayushatharva/brotli4j/native-linux-aarch64/. Just remove `.txt` extension (GitHub does not allow `.tgz` attachments).
=> Add native module for linux-aarch64

brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java
Return UnsatisfiedLinkError instead the result of #initCause(), i.e. a Throwable.
This way there is no need to declare 'throws' or try/catch at the caller site
=> Do not require the caller to try/catch Throwable

CMakeLists.txt, docker/Dockerfile.centos6
fix for build on centos6
- cmake directive
- change compiler to gcc5 to match the right ABI
=> fix CMakefile

pom.xml
Netty-Buffer 4.1.84.Final is released and we should upgrade to it.
=> Upgrade Netty-Buffer to 4.1.84.Final

brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/linux-aarch64/pom.xml, natives/linux-aarch64/src/main/java/com/aayushatharva/brotli4j/linux/aarch64/NativeLoader.java, natives/linux-x86_64/pom.xml, natives/linux-x86_64/src/main/java/com/aayushatharva/brotli4j/linux/x86_64/NativeLoader.java, natives/osx-aarch64/pom.xml, natives/osx-aarch64/src/main/java/com/aayushatharva/brotli4j/macos/aarch64/NativeLoader.java, natives/osx-x86_64/pom.xml, natives/osx-x86_64/src/main/java/com/aayushatharva/brotli4j/macos/x86_64/NativeLoader.java, natives/windows-x86_64/pom.xml, natives/windows-x86_64/src/main/java/com/aayushatharva/brotli4j/windows/x86_64/NativeLoader.java, pom.xml
Follow-up to #26
This system allows brotli4j to work in a JMPS environment while still working with Java 8 or newer non-modular setups.
I've based this on the work done in #26, but expanded it to the new arch (mac aarch64) and made it actually work in production environments.
The change of adding a new class to every native module is needed as when the jars are loaded in modular context, a class of one module cannot access the resources of another module.
I am not sure if there is a better way of doing this without sacrificing non-JMPS and j8 support, but this sould be fairly straightforward.
Fixes #24
Fixes #25
=> Fix Brotli4j not working at all in modular environments

brotli4j-tests/src/test/java/com/aayushatharva/brotli4j/encoder/EncoderTest.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java
Reference:
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/
=> avoid array allocation in Encoder.Mode.of

brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java
The intended auto-cleanup of the temporary directories which may be created by `Brotli4jLoader` for the native libraries isn't working as intended. I noticed more and more leftover directories piling up and never being removed again, at:
```
/tmp/com_aayushatharva_brotli4j_<timestamp>
```
Tiny fix to improve this, is to also register the extracted files in those directories for `deleteOnExit()` along.
=> Include extracted nativeLib-file in on-exit deletion of Brotli4jLoader

brotli4j/src/main/java/com/aayushatharva/brotli4j/common/Utils.java
Motivation:
We should have the option to determine the maximum compressed data size so it's easier to allocate a buffer for it ahead of compilation.
Modification:
Added Util method for it
Result:
Fixes #36
=> Add Util method for determining max compressed size

pom.xml
Motivation:
bump Netty version to latest (4.1.95)
https://netty.io/news/2023/07/20/4-1-95-Final.html
Modification:
changed Netty version number
Result:
Test suite passes.
=> netty 4.1.95

.github/workflows/maven.yml, README.md, all/pom.xml, brotli4j/pom.xml, brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java, natives/linux-ppc64le/build.sh, natives/linux-ppc64le/pom.xml, natives/linux-ppc64le/src/main/java/com/aayushatharva/brotli4j/linux/ppc64le/NativeLoader.java, natives/linux-x86_64/pom.xml, natives/pom.xml
Motivation:
This patch adds support for linux-ppc64le.
Modification:
Added ppc64le native module
Result:
ppc64le arch support
=> Add ppc64le architecture support

.github/workflows/maven.yml, docker/Dockerfile21.centos6, docker/docker-compose21.yml
Motivation:
JDK 21 is the new LTS and we should test Brotli4j on it for compatibility.
Modification:
Added JDK 21 builds.
Result:
JDK 21 CI builds.
=> Add JDK 21 Builds

pom.xml
Motivation:
The latest version of Netty is 4.1.104.Final. And we should upgrade to it.
Modification:
Updated Netty to 4.1.104.Final
Result:
Latest Netty version
=> Update Netty 4.1.104.Final

brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/EncoderJNI.java
Motivation:
This PR is aimed to mark EncoderJNI and EncoderJNI.Wrapper as public class since DecoderJNI and DecoderJNI.Wrapper are already public class. Meanwhile it also mark methods from EncoderJNI.Wrapper as public.
Modification:
Add public modifier in EncoderJNI and EncoderJNI.Wrapper.
Add public modifier in methods of EncoderJNI.Wrapper.
Result:
Fixes #123
=> Make EncoderJNI and EncoderJNI.Wrapper public

all/pom.xml
Motivation:
`all/pom.xml` had formatting issues which should be fixed.
Modification:
Fixed `all/pom.xml` formatting.
Result:
Clean `all/pom.xml` formatting.
=> Fix `all/pom.xml` formatting

brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java
Motivation:
Currently, the Java wrapper Encoder passes byte array length for finishing data encoding. This is ideal when the encoder is used with offset 0 and full length is passed but for cases where offset is passed and length is also specified, it leads to encoded data corruption.
Modification:
Instead of passing byte array length to the `push` method, we will now pass `length` directly.
Result:
Error-free encoding
=> Encoder wrong length during `push` op

README.md, all/pom.xml, brotli4j/pom.xml, natives/linux-aarch64/pom.xml, natives/linux-armv7/pom.xml, natives/linux-ppc64le/pom.xml, natives/linux-riscv64/pom.xml, natives/linux-s390x/pom.xml, natives/linux-x86_64/pom.xml, natives/osx-aarch64/pom.xml, natives/osx-x86_64/pom.xml, natives/pom.xml, natives/windows-aarch64/pom.xml, natives/windows-x86_64/pom.xml, pom.xml, service/pom.xml
=> Prepare for v1.15.0 release

natives/linux-x86_64/pom.xml
Motivation:
Module name for `linux-x86_64` native was broken,
Modification:
Updated correct Java Module name for `linux-x86_64`
Result:
JPMS works again
=> Fix Module Name for `linux-x86_64`

README.md
Motivation:
- document list of projects that use this library
Modification:
- add new section to README file
Result:
- README is updated
=> README: projects using brotli4j

brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/EncoderJNI.java
Motivation:
To allow for alternative Encoder use, make Encoder and EncoderJNI.Operation public.
Modification:
Made Encoder and EncoderJNI.Operation public.
Result:
Fixes #144
=> Make Encoder types public

brotli4j/src/test/java/com/aayushatharva/brotli4j/decoder/BrotliDecoderChannelTest.java
Motivation:
Noticed there were no tests for BrotliDecoderChannel, so here are a few for you to add.
Modification:
Created test cases for BrotliDecoderChannel.
Result:
See test cases
=> Add Tests of BrotliDecoderChannel

.github/workflows/maven.yml
Motivation:
`docker-compose` is no longer available and we should use `docker compose` plugin now.
Modification:
Updated workflows to use `docker compose` plugin
Result:
Build working again
=> Use docker compose plugin

pom.xml
Motivation:
Netty 4.1.112.Final is available and we should use it.
Modification:
Updated to Netty 4.1.112.Final
Result:
Up-to-date Netty version
=> Upgrade to Netty 4.1.112.Final

brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/EncoderJNI.java, brotli4j/src/test/java/com/aayushatharva/brotli4j/encoder/EncoderTest.java
Motivation:
As described in #189 the garbage collection currently removes the data from the dictionary, resulting in poor compression ratios, since no dictionary was actually used.
The code to finalize the rawData already exists.
Modification:
Hold the reference on rawData in PreparedDictionaryImpl
Result:
Fixes #189.
=> Avoid unintended garbage collection of raw data in PreparedDictionaryImpl

README.md, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/Encoder.java, brotli4j/src/test/java/com/aayushatharva/brotli4j/encoder/EncoderTest.java
**Motivation:**
Hello,
Currently, configuring `Encoder.Parameters` requires the following two steps:
1. Create an `Encoder.Parameters` object.
2. Use setter methods like `quality`, `lgwin`, or `mode` to configure it.
This approach can be unnecessarily complex and may lack clarity.
**Modification:**
In this PR, I propose adding static methods to configure `Encoder.Parameters` without explicitly creating an object. 
This makes the configuration process more intuitive and concise.
**Result:**
I believe this change will enhance code usability. 
I would appreciate your review!
Thanks.
=> Improve encoder parameter configuration

.github/dependabot.yml
Motivation:
Dependabot creates lots of PR at once, and it gets very noisy. Also, JUnit requires both `engine` and `api` to have same version but also breaks apart due to that.
Modification:
Run Dependabot monthly, limit the maximum PR to one for each ecosystem, and `groups` multiple PRs together.
Result:
Less noisy and clean dependabot updates
=> Make Dependabot less noisy

brotli4j/src/main/java/com/aayushatharva/brotli4j/decoder/BrotliInputStream.java, brotli4j/src/main/java/com/aayushatharva/brotli4j/encoder/BrotliOutputStream.java
Motivation:
Busy loops are blocking valuable threads, so other tasks are blocked while the current task spins waiting. This reduces concurrency without a need, hence makes inefficient use of the existing hardware.
Modification:
Using `Thread.yield()` in all busy waiting loops.
Result:
Other tasks are allowed to run while encode / decoder is busy.
=> Efficiency: Let thread do other tasks as long encoder/decoder is busy
